# Publish the joint states to joint_states.
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

left_steering_controller:
  joint: left_steer
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 40.0}
right_steering_controller:
  joint: right_steer
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 40.0}

left_front_axle_controller:
  joint: left_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_front_axle_controller:
  joint: right_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
left_rear_axle_controller:
  joint: left_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_rear_axle_controller:
  joint: right_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

pan_controller:
  joint: link_01_to_link_02
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 40.0}
tilt_controller:
  joint: link_02_to_link_03
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 40.0}
