#!/bin/bash

#source /opt/ros/$ROS_DISTRO/setup.bash

#if [[ -v ROS_WORKSPACE ]]
#then
#    source $ROS_WORKSPACE/devel/setup.bash
#else
#    source ~/catkin_ws/devel/setup.bash
#fi

source ~/.bashrc

rosservice call /set_k "k1: 1.0
k2: 6.0
k3: 3.0"

rosservice call /activate_controller "is_active: true"

rosservice call /run_task_manager

