#!/bin/bash

source /opt/ros/$ROS_DISTRO/setup.bash
source ~/lab_ws/devel/setup.bash


rosservice call /sherpa_1/set_k "k1: 1.0
k2: 6.0
k3: 9.0"
rosservice call /sherpa_2/set_k "k1: 1.0
k2: 6.0
k3: 9.0"


rosservice call /sherpa_1/activate_controller "is_active: true"
rosservice call /sherpa_2/activate_controller "is_active: true" 


rosservice call /sherpa_1/run_global_planner
rosservice call /sherpa_2/run_global_planner
