<?xml version="1.0"?>

<!-- Sherpa Wheels-->

<robot name ="sherpa_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Parameters -->
<xacro:property name="PI" value="3.1415926535897931"/>
  
  <!-- Wheel Parameters -->
  <xacro:property name="wheel_radius" value="0.16"/>
  <xacro:property name="wheel_width" value="0.11"/>
  
  <!-- Wheel Forces Parameters -->
  <xacro:property name="steer_joint_damping" value="0.01" />
  <xacro:property name="steer_joint_friction" value="0.01" />
  <xacro:property name="wheel_joint_damping" value="10.0" />
  <xacro:property name="wheel_joint_friction" value="15.0" />
  <xacro:property name="mu_1" value="1.5"/>
  <xacro:property name="mu_2" value="0.5"/>
  <xacro:property name="slip_1" value="0.5"/>
  <xacro:property name="slip_2" value="0.5"/>
  <xacro:property name="wheel_mass" value="1"/>
  
    <!-- Box Inertia -->
    <xacro:macro name="box_inertia" params="m h w d">
		<inertia 	ixx="${m*(w*w+d*d)/12}" ixy = "0" ixz = "0"
							iyy="${m*(d*d+h*h)/12}" iyz = "0"
							izz="${m*(w*w+h*h)/12}" />
	  </xacro:macro>
  
    <!-- Cylinder Inertia -->
    <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*r*r/2}" iyz = "0"
              izz="${m*(3*r*r+h*h)/12}" />
    </xacro:macro>

    <xacro:macro name="fake_inertial_wheel">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.01"/>
          <inertia
	      ixx="0.001" ixy="0.0" ixz="0.0"
	      iyy="0.001" iyz="0.0"
	      izz="0.001"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="fake_inertial">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="1e-5"/>
          <inertia
	      ixx="1e-6" ixy="0.0" ixz="0.0"
	      iyy="1e-6" iyz="0.0"
	      izz="1e-6"/>
        </inertial>
    </xacro:macro>

  
<!-- Left Steering Wheel -->
  
  <!-- Steering Mechanism -->
  <joint name="left_steer" type="revolute">
    <parent link="chassis"/>
    <child link="left_steer_link"/>
    <origin xyz="${0.8275-wheel_radius} ${0.4825-wheel_radius} 0.38"/>
    <limit effort="30.0" velocity="50.0" lower="-${PI/2}" upper="${PI/2}"/>
    <joint_properties damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="left_steer_link">
    <visual>   
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </visual>
    
 <!--   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </collision>
    -->
    <inertial> 
	    <origin rpy="0 0 0" xyz="0 0 0" />
	    <mass value="1.0" />
	    <cylinder_inertia m="1.0" r="0.16" h="0.02"/>
	  </inertial>

    <fake_inertial/>

  </link>
  <gazebo reference="left_steer_link"><material>Gazebo/Black</material></gazebo>
  
  <!-- suspension -->
  <joint name="left_front_suspension_joint" type="fixed">
    <parent link="left_steer_link"/>
    <child link="left_front_suspension"/>
    <origin xyz="0 0.0350 0"/>
  </joint>
  
  <link name="left_front_suspension">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </visual>
    
  <!--  <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 -0.09" />-->
<!--	    <mass value="1.0" />-->
<!--	    <box_inertia  m="1.0" h="0.04" w ="0.04" d="0.16"/>-->
<!--	  </inertial>-->
    <fake_inertial/>
  </link>
  <gazebo reference="left_front_suspension"><material>Gazebo/Black</material></gazebo>
    
   <!-- wheel -->
   
  <joint name="left_front_axle" type="continuous">
      <parent link="left_front_suspension" />
      <child link="left_front_wheel"/>
      <origin xyz="0 0.020 -0.18"/>
      <axis xyz="0 1 0"/>
	    <joint_properties damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>
   
  <link name="left_front_wheel">
    <visual>
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
            
    <collision>        
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial> 
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
	    <mass value="${wheel_mass}" />
	    <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
	  </inertial>
  </link>
  <gazebo reference="left_front_wheel">
    <material>Gazebo/Grey</material>
    <mu1 value="${mu_1}"/>
    <mu2 value="${mu_2}"/>  
    </gazebo>
    

<!-- Right Steering Wheel -->
  
  <!-- Steering Mechanism -->
  <joint name="right_steer" type="revolute">
    <parent link="chassis"/>
    <child link="right_steer_link"/>
    <origin xyz="${0.8275-wheel_radius} -${0.4825-wheel_radius} 0.38"/>
    <limit effort="30.0" velocity="50.0" lower="-${PI/2}" upper="${PI/2}"/>
    <joint_properties damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="right_steer_link">
    <visual>   
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </visual>
    
 <!--   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </collision>
    -->
    <inertial> 
	    <origin rpy="0 0 0" xyz="0 0 0" />
	    <mass value="1.0" />
	    <cylinder_inertia m="1.0" r="0.16" h="0.02"/>
	  </inertial>
  </link>
  <gazebo reference="right_steer_link"><material>Gazebo/Black</material></gazebo>
  
  <!-- suspension -->
  <joint name="right_front_suspension_joint" type="fixed">
    <parent link="right_steer_link"/>
    <child link="right_front_suspension"/>
    <origin xyz="0 -0.035 0"/>
  </joint>
  
  <link name="right_front_suspension">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </visual>
    
  <!--  <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 -0.09" />-->
<!--	    <mass value="1.0" />-->
<!--	    <box_inertia  m="1.0" h="0.04" w ="0.04" d="0.16"/>-->
<!--	  </inertial>-->
    <fake_inertial/>

  </link>
  <gazebo reference="right_front_suspension"><material>Gazebo/Black</material></gazebo>
    
   <!-- wheel -->
   
  <joint name="right_front_axle" type="continuous">
      <parent link="right_front_suspension" />
      <child link="right_front_wheel"/>
      <origin xyz="0 -0.020 -0.18"/>
      <axis xyz="0 1 0"/>
      <joint_properties damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>
   
  <link name="right_front_wheel">
    <visual>
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
            
    <collision>        
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial> 
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
	    <mass value="${wheel_mass}" />
	    <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
	  </inertial>
  </link>
  
  <gazebo reference="right_front_wheel">
    <material>Gazebo/Grey</material>
    <mu1 value="${mu_1}"/>
    <mu2 value="${mu_2}"/>    
  </gazebo>
  
  
<!-- Left rear Wheel -->
  
  <!-- Support-->
  <joint name="left_support_joint" type="fixed">
    <parent link="chassis"/>
    <child link="left_support_link"/>
    <origin xyz="-${0.8275-wheel_radius} ${0.4825-wheel_radius} 0.38"/>
    <joint_properties damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="left_support_link">
    <visual>   
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </visual>
    
 <!--   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 0" />-->
<!--	    <mass value="1.0" />-->
<!--	    <cylinder_inertia m="1.0" r="0.16" h="0.02"/>-->
<!--	  </inertial>-->
    <fake_inertial/>
  </link>
  <gazebo reference="left_support_link"><material>Gazebo/Black</material></gazebo>
  
  <!-- suspension -->
  <joint name="left_rear_suspension_joint" type="fixed">
    <parent link="left_support_link"/>
    <child link="left_rear_suspension"/>
    <origin xyz="0 0.035 0"/>
  </joint>
  
  <link name="left_rear_suspension">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </visual>
<!--    
    <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 -0.09" />-->
<!--	    <mass value="1.0" />-->
<!--	    <box_inertia  m="1.0" h="0.04" w ="0.04" d="0.16"/>-->
<!--	  </inertial>-->
    <fake_inertial/>
  </link>
  <gazebo reference="left_rear_suspension"><material>Gazebo/Black</material></gazebo>
    
   <!-- wheel -->
   
  <joint name="left_rear_axle" type="continuous">
      <parent link="left_rear_suspension" />
      <child link="left_rear_wheel"/>
      <origin xyz="0 0.020 -0.18"/>
      <axis xyz="0 1 0"/>
      <joint_properties damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>
   
  <link name="left_rear_wheel">
    <visual>
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
            
    <collision>        
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial> 
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 0.055 0"/>
	    <mass value="${wheel_mass}" />
	    <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
	  </inertial>
  </link>

  <gazebo reference="left_rear_wheel">
    <material>Gazebo/Grey</material>
    <mu1 value="${mu_1}"/>
    <mu2 value="${mu_2}"/>  
  </gazebo>
    

<!-- Right Steering Wheel -->
  
  <!-- Support -->
  <joint name="right_support_joint" type="fixed">
    <parent link="chassis"/>
    <child link="right_support_link"/>
    <origin xyz="-${0.8275-wheel_radius} -${0.4825-wheel_radius} 0.38"/>
    <limit effort="30.0" velocity="50.0" lower="-${PI/2}" upper="${PI/2}"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <link name="right_support_link">
    <visual>   
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </visual>
    
 <!--   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.16" length="0.02"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 0" />-->
<!--	    <mass value="1.0" />-->
<!--	    <cylinder_inertia m="1.0" r="0.16" h="0.02"/>-->
<!--	  </inertial>-->
    <fake_inertial/>
  </link>
  <gazebo reference="right_support_link"><material>Gazebo/Black</material></gazebo>
  
  <!-- suspension -->
  <joint name="right_rear_suspension_joint" type="fixed">
    <parent link="right_support_link"/>
    <child link="right_rear_suspension"/>
    <origin xyz="0 -0.035 0"/>
  </joint>
  
  <link name="right_rear_suspension">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </visual>
<!--    
    <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.09"/>
      <geometry>
        <box size="0.04 0.04 0.16"/>
      </geometry>
    </collision>
    -->
<!--    <inertial> -->
<!--	    <origin rpy="0 0 0" xyz="0 0 -0.09" />-->
<!--	    <mass value="1.0" />-->
<!--	    <box_inertia  m="1.0" h="0.04" w ="0.04" d="0.16"/>-->
<!--	  </inertial>-->
    <fake_inertial/>
  </link>
  <gazebo reference="right_rear_suspension"><material>Gazebo/Black</material></gazebo>
    
   <!-- wheel -->
   
  <joint name="right_rear_axle" type="continuous">
      <parent link="right_rear_suspension" />
      <child link="right_rear_wheel"/>
      <origin xyz="0 -0.020 -0.18"/>
      <axis xyz="0 1 0"/>
      <joint_properties damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>
   
  <link name="right_rear_wheel">
    <visual>
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
            
    <collision>        
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial> 
      <origin rpy="0 ${PI/2} ${PI/2}" xyz="0 -0.055 0"/>
	    <mass value="${wheel_mass}" />
	    <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
	  </inertial>
  </link>
  
  <gazebo reference="right_rear_wheel">
    <material>Gazebo/Grey</material>
    <mu1 value="${mu_1}"/>
    <mu2 value="${mu_2}"/>  
  </gazebo>
  
  <!-- 
    <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>200.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>left_front_axle</leftFrontJoint>
      <rightFrontJoint>right_front_axle</rightFrontJoint>
      <leftRearJoint>left_rear_axle</leftRearJoint>
      <rightRearJoint>right_rear_axle</rightRearJoint>
      <wheelSeparation>0.855</wheelSeparation>
      <wheelDiameter>0.16</wheelDiameter>
      <robotBaseFrame>sherpa/base_link</robotBaseFrame>
      <torque>1</torque>
      <topicName>sherpa/akrm_cmd</topicName>
      <broadcastTF>true</broadcastTF>
    </plugin>
  </gazebo>
  
  -->
  
<!-- Include sherpa_wheel_transmission -->
<xacro:include filename="sherpa_wheel_transmission_ackermann.xacro"/>
  
</robot>
